apiVersion: v1
kind: Namespace
metadata:
  name: synergy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: synergy-deployment
  namespace: synergy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synergy
  template:
    metadata:
      labels:
        app: synergy
    spec:
      containers:
      - name: app
        image: busybox
        command: ["sh","-c"]
        args:
        - |
          i=0
          while true; do
            echo "synergy log line=$i" >> /var/log/synergy-deployment.log
            i=$((i+1))
            sleep 2
          done
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      volumes:
      - name: varlog
        emptyDir: {}
