apiVersion: v1
kind: Namespace
metadata:
  name: gateway-migration
---
apiVersion: v1
kind: Secret
metadata:
  name: web-tls
  namespace: gateway-migration
type: kubernetes.io/tls
data:
  tls.crt: ZHVtbXk=
  tls.key: ZHVtbXk=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: gateway-migration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: web
        image: nginx:1.25
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-svc
  namespace: gateway-migration
spec:
  selector:
    app: webapp
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  namespace: gateway-migration
spec:
  tls:
  - hosts: ["gateway.web.k8s.local"]
    secretName: web-tls
  rules:
  - host: gateway.web.k8s.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webapp-svc
            port:
              number: 80
