apiVersion: v1
kind: Namespace
metadata:
  name: relative-fawn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: relative-fawn
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      initContainers:
      - name: init
        image: busybox
        command: ["sh","-c","echo init; sleep 1"]
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
      containers:
      - name: wp
        image: nginx:1.25
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
