apiVersion: v1
kind: Namespace
metadata:
  name: priority
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-logger
  namespace: priority
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-logger
  template:
    metadata:
      labels:
        app: busybox-logger
    spec:
      containers:
      - name: logger
        image: busybox
        command: ["sh","-c","while true; do date; sleep 3; done"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: other-app
  namespace: priority
spec:
  replicas: 2
  selector:
    matchLabels:
      app: other-app
  template:
    metadata:
      labels:
        app: other-app
    spec:
      containers:
      - name: app
        image: busybox
        command: ["sh","-c","while true; do echo other; sleep 5; done"]
